define(
    [
        "css!./theme/midnight.css",
        "css!./theme/blackboard.css",
        "css!./theme/solarized.css",
        "css!./theme/yeti.css",
        "css!./theme/base16-light.css",
        "css!./theme/eclipse.css",
        "css!./theme/vibrant-ink.css"
    ]
);